
Error parsing \"/var/lib/prometheus/node-exporter/sentinel.db.prom\": text format parsing error in line 7: unexpected end of label value \"\"" source="textfile.go:211"


sentinel_watch_syslog_rule_engine{config="watch-syslog-stream",rule="rule-4",b2sum="2f9212bd3c5b2e4dea560f116e98b7ef07de50bc",seen="False",data=""time=\"2021-03-11T18:40:18Z\" level=error msg=\"ERROR: xfs collector failed after 0.000489s: failed to retrieve XFS stats: incorrect number of values for XFS quota stats: 9\" source=\"collector.go:132\"""} 1

# data=""time=\"2021


Mar 11 11:52:18 prometheus1 prometheus-node-exporter[669]: time="2021-03-11T19:52:18Z" level=error msg="ERROR: xfs collector failed after 0.000420s: failed to retrieve XFS stats: incorrect number of values for XFS quota stats: 9" source="collector.go:132"
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]: Process Process-2:
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]: Traceback (most recent call last):
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:   File "/usr/libexec/sentinel/runtime/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:     self.run()
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:   File "/usr/libexec/sentinel/runtime/lib/python3.8/multiprocessing/process.py", line 108, in run
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:     self._target(*self._args, **self._kwargs)
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:   File "/usr/libexec/sentinel/tools.py", line 866, in sentryLogStream
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:     if rule_hit: updategDictR(_key, gDict, rule_hit, r, line, db_store, verbose)
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:   File "/usr/libexec/sentinel/tools.py", line 790, in updategDictR
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:     store_occurrence = store.replaceINTOtrio('occurrence', str(_k), str(r[b]), line, db_store)
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:   File "/usr/libexec/sentinel/store.py", line 685, in replaceINTOtrio
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]:     con.commit()
Mar 11 11:52:20 prometheus1 sentinel.py[2978865]: sqlite3.OperationalError: database is locked



