
Exception in thread SentryJobRunner:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/sentinel/python/tools.py", line 2071, in sentryProcessJobs
    if now_time > delta_time:
  File "/opt/sentinel/python/tools.py", line 1924, in runJob

TypeError: psCheck() takes 0 positional arguments but 2 were given


this should be fix'd

